pipeline
{
  options
  {
      buildDiscarder(logRotator(numToKeepStr: '5'))
  }
    
  agent {label 'USTR-MVM-1481'}
  stages 
  {     
    stage('Approval')
    {
      steps
      {
        node ('USTR-MVM-1481')
        {
          ws('/usr/local/cmpapprove')
          {
              sh '''

              echo "You clicked on Yes."

              '''
          }            
        }
      }
    } 

    stage('Approval for destroying terraform resources and cleaning workspace')
    {
      steps
      {
        node ('USTR-MVM-1481')
        {
          ws('/usr/local/cmpapprove')
          { 
            script
            { 
              def mailRecipients = 'k.dandapath@unisys.com,vishal.gupta2@unisys.com'
              def approversList = 'DandapK1,GuptaVi1,KumarRa7'
              def jobName = currentBuild.fullDisplayName
              def userAborted = false
              emailext body: '''
              Please go to console output of ${BUILD_URL}input to approve or Reject.<br>
              ''',    
              mimeType: 'text/html',
              subject: "[Jenkins] ${jobName} Build Approval Request",
              to: "${mailRecipients}",
              replyTo: "${mailRecipients}",
              recipientProviders: [[$class: 'CulpritsRecipientProvider']]

              echo "Building1"
              try 
              { 
                userInput = input submitter: "${approversList}", message: 'Do you approve?'
              } 
              catch (org.jenkinsci.plugins.workflow.steps.FlowInterruptedException e) 
              {
                cause = e.causes.get(0)
                echo "Aborted by " + cause.getUser().toString()
                userAborted = true
                echo "SYSTEM aborted, but looks like timeout period didn't complete. Aborting."
              }
              if (userAborted) 
              {
                currentBuild.result = 'ABORTED'
              } 
              else 
              {
                echo "Building2"
              }
            }
          }
        }
      }
    }
        
    stage('Post Approval Stage')
    {		   
      steps
      {
        node ('USTR-MVM-1481')
        {
          ws('/usr/local/cmpapprove')
            {
              sh '''

              echo "Post approval stage"

              '''
            }            
          }
        }
    }         
  }
}
