{{- if .Values.tests.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mariadb.fullname" . }}-tests
  namespace: {{ .Values.namespace }}
data:
  run.sh: |-
    @test "Testing MariaDB is accessible" {
      mysql -h {{ template "mariadb.fullname" . }} -uroot -p$MARIADB_ROOT_PASSWORD -e 'show databases;'
    }
{{- end }}
