---
# tasks file for install_package
- name: Install Apache
  yum:
    name: "httpd"
    state: present
    #update_cache: yes

- name: Start the Service
  service:
    name: "httpd"
    state: restarted
    enabled: yes
#- name: Install Epel-Release
#  yum:
#    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
#    state: present


#- name: Install Epel-Release
#  yum:
#    name: epel-release
#    state: present

- name: Install basic packages
  package:
    name: ['vim','wget','unzip','curl','git']
    state: present


################## Optional Component - Uncomment if Needed ################################
# - name: Install Java 8 
#   yum:
#    name: java-1.8.0-openjdk
#    state: present

# - name: Add tomcat group
#   group:
#     name: tomcat

# - name: Add "tomcat" user
#   user:
#     name: tomcat
#     group: tomcat
#     home: /usr/share/tomcat
#     createhome: no
#     system: yes

# - name: Download Tomcat
#   get_url:
#     url: "{{ tomcat_archive_url }}"
#     dest: "{{ tomcat_archive_dest }}"

# - name: Create a tomcat directory
#   file:
#     path: /usr/share/tomcat
#     state: directory
#     owner: tomcat
#     group: tomcat

# - name: Create a tomcat directory
#   file:
#     path: /usr/share/tomcat/bin
#     state: directory
#     owner: tomcat
#     group: tomcat

# - name: Extract tomcat archive
#   unarchive:
#     src: "{{ tomcat_archive_dest }}"
#     dest: /usr/share/tomcat/
#     owner: tomcat
#     group: tomcat
#     remote_src: yes
#     extra_opts: "--strip-components=1"


# - name: Copy tomcat service file
#   template:
#     src: templates/tomcat.service.j2
#     dest: /etc/systemd/system/tomcat.service
#   when: ansible_service_mgr == "systemd"

# - name: Start and enable tomcat
#   service:
#     daemon_reload: yes
#     name: tomcat
#     state: started
#     enabled: yes
#   when: ansible_service_mgr == "systemd"

# - name: Reboot a Linux machine 
#   reboot:
#     test_command: uptime

