---
- hosts: all
  tasks:
    - name: check if a file exists
      win_stat:
        path: C:\\Program Files\\Cybereason ActiveProbe\\CrsSvc.exe
      register: register_name
    - name: Task name
      debug:
        msg: "The file or directory exists"
      when: register_name.stat.exists
    - name: Report missing file
      debug:
        msg: " The file or directory doesn't exists"
      when: not register_name.stat.exists
    - name: copy Cybereason
      win_get_url:
        url: http://ustr-erl-5764.na.uis.unisys.com/Chef_LoadPoints/cybereason/CybereasonDesktopInstall_20.1.362.0_u1.8.exe
        dest: C:\Temp
      when: not register_name.stat.exists
    - name: install cybereason
      win_command: C:\Temp\CybereasonDesktopInstall_20.1.362.0_u1.8.exe /q
      when: not register_name.stat.exists