---
- name: Ansible Copy Directory Example Local to Remote
  hosts: all
  tasks:
    - name: Copying the Directory's contents (sub directories/files)
      become: true 
      copy:
        src: /var/opt/morpheus/morpheus-ui/repo/git/4a201487bb5b7d659272bf2ff13de760/Hybrid-Cloud/phpcode/
        dest: /var/www/html/