---
- name: Ansible Copy Directory Example Local to Remote
  hosts: all
  tasks:
    - name: Install latest version of Apache
      apt: name=apache2 update_cache=yes state=latest
    - name: Copying the Directory's contents (sub directories/files)
      become: true 
      copy:
        src: /var/opt/morpheus/morpheus-local/repo/git/4a201487bb5b7d659272bf2ff13de760/Hybrid-Cloud/phpcode/
        dest: /var/www/html/
        
    - name: deleting the index.html
      become: true
      shell: "rm -f /var/www/html/index.html"