--- 
- 
  hosts: all
  name: "Ansible Copy Directory Example Local to Remote"
  tasks: 
    - 
      become: true
      copy: 
        dest: /tmp/
        src: /var/opt/morpheus/morpheus-local/repo/git/4a201487bb5b7d659272bf2ff13de760/Hybrid-Cloud/mysql_db_table_creation.sh
      name: "Copying the Directory's contents (sub directories/files)"
    - 
      become: true
      command: chmod +x /tmp/mysql_db_table_creation.sh
      name: "Give permissions to the mysql db script"
    - 
      become: true
      name: "Created database and users table in mysql database"
      shell: "bash /tmp/mysql_db_table_creation.sh"
