---
- name: Ansible Copy Directory Example Local to Remote
  hosts: all
  vars:
	ansible_python_interpreter: /usr/bin/python3
  roles:
	- { role: install_package_linux }
  tasks:
    - name: Copying the Directory's contents (sub directories/files)
      become: true 
      copy:
        src: /var/opt/morpheus/morpheus-local/repo/git/4a201487bb5b7d659272bf2ff13de760/Hybrid-Cloud/phpcode/
        dest: /var/www/html/
        
    - name: deleting the index.html
      become: true
      shell: "rm -f /var/www/html/index.html"